# Generated by Django 4.2.7 on 2024-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
    ]
