# Generated by Django 4.2.7 on 2024-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='e_mail',
            field=models.CharField(max_length=50, unique=True, verbose_name='E-mail'),
        ),
    ]
