# Generated by Django 4.2.7 on 2024-02-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('mini_description', models.TextField(blank=True, null=True, verbose_name='Мини описание')),
                ('image', models.ImageField(blank='True', null=True, upload_to='goods_image', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена со скидкой')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('sub_category', models.CharField(choices=[('---', '---'), ('shoes', 'Обувь'), ('Outerwear', 'Верхняя одежда'), ('t_shirts', 'Футболки'), ('trousers', 'брюки'), ('Costumes', 'Костюмы'), ('Sportswear', 'Спортивная одежда'), ('Accessories', 'Аксессуары'), ('Dresses', 'Платья'), ('Overall', 'Комбинезоны'), ('sundresses', 'сарафаны')], default='---', max_length=150, verbose_name='Подкатегория')),
                ('articul', models.CharField(max_length=5, unique=True, verbose_name='Артикул')),
                ('country', models.CharField(blank=True, max_length=150, verbose_name='Страна производства')),
                ('size', models.CharField(blank=True, max_length=2, verbose_name='Размер')),
                ('structure', models.CharField(blank=True, max_length=400, verbose_name='Состав')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
    ]
